version: "3.8"

services:
  model_server:
    build: .
    environment:
      - LABEL_STUDIO_HOST=http://xx.xx:5010 # Need to update host for new instances of label studio 
      - LABEL_STUDIO_API_KEY= # Need to update api key for new instances of label studio. Can be found in label studio settings.
      - TZ=Asia/Shanghai
      - NVIDIA_VISIBLE_DEVICES=MIG-f3c77f5e-30d7-5ee8-b28c-1ec2c86c24ca
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
    ports:
      - 5011:9090 # Need to update port, eg. 5000,5001,5002,5003,5004.. for new instances of label studio **backend**. 
    volumes:
      - .:/app/
    shm_size: '16gb' # Added larger shared memory for deep learning
    networks:
      - ml_network
    restart: always
    runtime: nvidia

networks:
  ml_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.30.0.0/16 # Need to update subnet for new instances of label studio **backend**. To avoid conflict with other networks.
